name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Выкачиваем репозиторий
      - uses: actions/checkout@v4

      # Настраиваем Java (исправленные отступы!)
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'  # Теперь с правильным отступом (2 пробела)
          java-version: '21'
      - uses:  Xotabu4/selenoid-github-action@v2
      # Запускаем тесты
      - run: mvn clean test -Dselenide.remote=http://localhost:4444/wd/hub
